### ISSUE TITLE
Error: Cannot Read Property 'then ' of Undefined

### ISSUE THREAD

**Issue by jashah46** [nss-day-cohort-46/How-to-Ask-for-Help#26] opened 2021-02-19 16:43 UTC
#### Have you searched the other issue tickets? If not, do that first. 
- [X ] Yes
- If No, stop and search.

####  REQUIRED Add Tags to Issue Ticket and Assign to Project Board
 

- [x ] Added label to specific project/assignment that you need help with
- [ ] Added to `c46 Help-Thread` project board

#### REQUIRED Describe your issue:
>> We're getting an error of undefined and we're now time boxed.  We could use some help. 

#### REQUIRED List any error messages that appear:

ProductList.js:13 Uncaught TypeError: Cannot read property 'then' of undefined
    at ProductList (ProductList.js:13)
    at main.js:14
#### REQUIRED What have you googled? 

- [ ] 1. https://stackoverflow.com/questions/11355854/how-to-show-a-message-in-the-login-page-if-the-login-fails-using-javascript
- [ ] 2. https://stackoverflow.com/questions/24788171/typeerror-cannot-read-property-then-of-undefined
- [ ] 3. https://www.pluralsight.com/guides/javascript-promise-typeerror:-cannot-read-then-of-undefined

#### REQUIRED: What have you tried? Tell us everything you have tried. 
>> We checked all the tickets.  We found one that was like ours, where Jisie suggested site no. 3 above, but we are just spinning wheels. 

#### REQUIRED: Copy/paste link TO THE FILE on your branch that you are having issues with

https://github.com/nss-day-cohort-46/sprinkles-of-joy-tatooine-tort/blob/main/scripts/products/ProductList.js

#### Code Snippet

```
export const ProductList = () => {
  getProducts()
    .then(getCategories)
    .then(() => {
      bakeryProducts = useProducts()
      bakeryCategories = useCategories()
      render(getCategories)
    })
}

```

**Comment by ajawashington** [comment] 2021-02-19 16:47
Refer to your Category Provider, and the "getCategories" fetch call.

**Comment by jashah46** [comment] 2021-02-19 17:34
we added "return" before categories.slice but we still have an error.

**Comment by Scott47** [comment] 2021-02-19 17:38
@jashah46 have you read the article @jisie suggested? Any progress.

**Comment by jashah46** [comment] 2021-02-19 17:41
We have and we are no closer to resolving it.

**Comment by jisie** [comment] 2021-02-19 17:41
Duplicate of #14

**Closed** 2021-02-19 17:58 UTC
Labels: bug, duplicate, help wanted
